### ISSUE TITLE
Refactor planning for v2

### ISSUE THREAD

**Issue by robertleeplummerjr** [gpujs/gpu.rocks#7]

**Comment by HarshKhandeparkar** [comment]
Copying in Robert's coment

> Can you propose a plan here: gpujs/gpu.rocks#7
That is the repository for the website.
If you'd like to experiment with the code, it is all there to play with

My plan draft:
1. Explain GPGPU from ground up. Explain when the gpu is more effective compared to cpu. Explain use cases.
2. Explain every line of code.(most of it)
3. Explain how heavy matrix multiplication can be on the cpu.
4. Explain what things the gpu can and cannot do (e.g. complex math funcs, if...else)
5. Graphs. We can graph performance values of different sized matrix multiplication and graph them to show the break even point between gpu and cpu performance.
6. Document the most important methods in detail on the main website itself. (createKernel, build, different modes)
7. Add more code examples.
8. Improve the website in general (just an added bonus).

cc @robertleeplummerjr

**Comment by HarshKhandeparkar** [comment]
@robertleeplummerjr I have put together [this](https://codepen.io/imnotacoder/pen/KEyYjm) codepen for benchmark comparison. Have a look at it.

**Comment by robertleeplummerjr** [comment]
Ty for taking the initiative on this!  When I run the codepen, all numbers come out zero's and the page refreshes.  I'm running chrome on osx, fyi.

**Comment by robertleeplummerjr** [comment]
Linking in related issues as they come up.  First winner: https://github.com/gpujs/gpu.js/issues/451

**Comment by HarshKhandeparkar** [comment]
I fixed the page refresh. Materiallze js wqs causing some problem. Btw, everything other than texture mode is commented.

**Comment by HarshKhandeparkar** [comment]
@robertplummerleejr I have fixed all errors and kinda finalized my pen. You can see it in debug view here https://s.codepen.io/imnotacoder/debug/KEyYjm/ZoABaKqnoDQr.

Btw, can I change the CSS framework the website uses (if it uses one)? Can I kind of do an overhaulish thing? The page is a bit unresponsive and buggy. I want to change that and also change its looks and content.

**Comment by robertleeplummerjr** [comment]
>You can see it in debug view here

I really like the example you gave!  Can you make it so if you click somewhere we can see the code used to make the test?  

>Btw, can I change the CSS framework the website uses (if it uses one)?

We're open to making it simple and current, so change what you like, and keep that in mind.  We want responsive and not buggy.  With how the page looks, I'm not sure but I'm sure we'd be open to proposals.

**Comment by HarshKhandeparkar** [comment]
You can go to the original codepen link I had given you. It is the code for it.

**Comment by HarshKhandeparkar** [comment]
I am actually editing it right now. One min and I'll give you a fresh link.

**Comment by HarshKhandeparkar** [comment]
Done With it.
* [code](https://codepen.io/imnotacoder/pen/KEyYjm)
* [full-page-demo](https://s.codepen.io/imnotacoder/debug/KEyYjm/gakeYZPeBLJk)

@robertleeplummerjr

**Comment by robertleeplummerjr** [comment]
I meant, in the page itself, like click and see the code, so the person running the code gets a quick idea of how they are related.

**Comment by HarshKhandeparkar** [comment]
Who will see the codepen code? Or even the pen? No problem though, I’ll add that in a min

**Comment by HarshKhandeparkar** [comment]
I actually need your help here. I added the link and also added a new feature but it isn’t working. Can you please help me.
?

**Comment by HarshKhandeparkar** [comment]
@robertleeplummerjr

**Comment by HarshKhandeparkar** [comment]
Let’s discuss this in gitter.

**Comment by HarshKhandeparkar** [comment]
Hey I got the error. The problem is that the array goes out of bounds because of the convolved kernel. Trying to fix it.

**Comment by HarshKhandeparkar** [comment]
@robertleeplummerjr I have forked the pen myself(by mistake).
[Here](https://codepen.io/imnotacoder/pen/NmyWmx) is the updated link

**Comment by HarshKhandeparkar** [comment]
Btw, what is your timezone? Tell me relative to UTC(GMT) e.g. GMT+5.30

**Comment by HarshKhandeparkar** [comment]
Another question, is `Math.random()` supported?

**Comment by robertleeplummerjr** [comment]
`Math.random()` is cautiously supported in v2.  I say "cautiously" because it isn't as good of quality of random on the CPU, but it should be enough for most use cases.  This is because of the fact we want it to be fairly fast, and the nature of GPU's not having as much of a connection to other data than precisely what it is sent and what it is provided from opengl.

**Comment by robertleeplummerjr** [comment]
@HarshKhandeparkar As far as timezone, be careful not to be too explicit with your location and data, as this is all public information.  I'm -5 GMT.

**Comment by HarshKhandeparkar** [comment]
Ok. Thanks for the info. Btw, timezone isn't much of a problem as my whole country has the same timezone and I don't mind sharing location as it is shown in my profile already. Btw, did you get the link? https://github.com/gpujs/gpu.rocks/issues/7#issuecomment-484044883

**Comment by robertleeplummerjr** [comment]
Got it, I will investigate later today.

**Comment by HarshKhandeparkar** [comment]
Ok thanks.

**Comment by robertleeplummerjr** [comment]
From: https://github.com/gpujs/gpu.js/issues/451

>Likewise, I feel sections on Useful Kernels and How to Write efficient Kernels would be much appreciated.

**Comment by HarshKhandeparkar** [comment]
Ok. Will you be free today? I can start doing the work but I will need
some(very little) assistance/guidance.

**Comment by robertleeplummerjr** [comment]
Yes.  The big push I was going for has been met and released in [v2 rc7](https://github.com/gpujs/gpu.js/releases/tag/2.0.0-rc.7).

**Comment by HarshKhandeparkar** [comment]
Ok. Nice. Any specific time from now? Like 2hrs from now?

**Comment by robertleeplummerjr** [comment]
Now would be fine.

**Comment by HarshKhandeparkar** [comment]
@robertleeplummerjr I am getting weird errors. I have messaged you on gitter about it.
